### ISSUE TITLE
開発環境のコンテナ化：Dockerfile と docker-compose の追加

### ISSUE THREAD

**Issue by yuya-matsushima** [fillin-inc/timeins#6]
## 概要
開発環境の統一化とClaude開発での利便性向上のため、Dockerコンテナ環境を整備します。

## 背景
- 開発者間での環境差異を解消
- 新規開発者のオンボーディング簡素化
- Claude AIでの開発時の環境統一
- CI環境との一貫性確保

### 1. Dockerfile
```dockerfile
# マルチステージビルド対応
# 開発環境とプロダクション環境の両方に対応
FROM golang:1.23-alpine AS dev
WORKDIR /app
RUN apk add --no-cache git make
RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
COPY go.mod go.sum ./
RUN go mod download
```

### 2. docker-compose.yml
```yaml
version: '3.8'
services:
  dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    command: make test
```

### 3. .devcontainer/devcontainer.json
VS Code Dev Container統合用の設定

## タスク
- [ ] 開発用Dockerfileの作成
- [ ] docker-compose.ymlの作成
- [ ] .devcontainer設定の追加
- [ ] Makefileにdocker関連コマンドを追加
- [ ] .dockerignoreファイルの作成
- [ ] READMEにDocker使用方法を追記

## 期待される効果
- `docker-compose up`で即座に開発環境構築
- VS CodeのDev Container機能で統一された開発環境
- CI環境と同じ条件でのローカルテスト実行

## 優先度
🟢 **中** - 開発効率の向上
